### ISSUE TITLE
Invalid plugin file

### ISSUE THREAD

**Issue by mornir** [JessicaSachs/vue-cli-plugin-cypress-experimental#1]
Hi!
First thank you for your work on cypress-vue-unit-test 😀 I think that there's a big potential in using Cypress for components integration tests.

On a [fresh install](https://github.com/mornir/cypress-laracast-vue-testing), I get this error when I run `yarn test:components`
![image](https://user-images.githubusercontent.com/1411843/80689695-fdd8e400-8acd-11ea-9b50-d6753f4458dd.png)

When disabling plugins, Cypress runs fine.

**Comment by JessicaSachs** [comment]
You are correct! Lol I'm so happy you wrote this issue. I just pulled everything down for an e2e test and am now pushing a fix.

**Comment by JessicaSachs** [comment]
Fixed in v0.0.4 of the plugin. This is what you should see on the first run of 

`npm run test:components`

![Screen Shot 2020-04-30 at 7 21 35 PM](https://user-images.githubusercontent.com/2801156/80768250-e3c3f380-8b17-11ea-800a-71e13c283ab9.png)

**Comment by mornir** [comment]
Awesome! 🙌

**Comment by mornir** [comment]
Ah, it was a syntax error because of the mix usage of ESM imports?
I actually tried to fix it by replacing `module.exports` with `export default`... wrong way around 😅

**Comment by JessicaSachs** [comment]
Yeah, when I was developing locally I was running with a different babel configuration so it was working. This is why I'm working on #3
